module.exports = {
  profile: {
    name: 'Muhammad Jasim Munir',
    headline: 'Software Engineering Student · Web Developer · Backend Learner',
    location: 'Lahore, Punjab, Pakistan',
    email: 'mjmflux@icloud.com',
    phone: '+923285958656',
    summary:
      'Software Engineering student with hands-on experience in software development, focusing on data structures, algorithms, and backend system design. Built multiple academic projects including a task scheduling system inspired by Jira, implementing core backend logic and workflow management. Skilled in C++, JavaScript, and web fundamentals with a strong problem-solving mindset. Actively seeking a Software Engineering Internship to contribute to real-world engineering teams and further develop scalable system-building expertise.',
    avatar: '',
    resumeUrl: '/resume.pdf',
    socials: {
      github: 'https://github.com/Muhammad-Jasim-Munir',
      linkedin: 'http://linkedin.com/in/muhammad-jasim-enflux',
      twitter: '',
    },
    seo: {
      title: 'Muhammad Jasim Munir — Software Engineering Student & Developer',
      description:
        'Portfolio of Muhammad Jasim Munir — Software Engineering student building backend systems, full-stack apps, and DSA-driven projects.',
      keywords: ['Muhammad Jasim Munir', 'Software Engineer', 'C++', 'MERN', 'Portfolio', 'Lahore'],
    },
  },

  skills: [
    { name: 'C++', category: 'Languages', level: 90, order: 1 },
    { name: 'JavaScript', category: 'Languages', level: 80, order: 2 },
    { name: 'HTML', category: 'Web', level: 90, order: 3 },
    { name: 'CSS', category: 'Web', level: 85, order: 4 },
    { name: 'Data Structures & Algorithms', category: 'Core CS', level: 85, order: 5 },
    { name: 'Node.js', category: 'MERN (Learning)', level: 60, order: 6 },
    { name: 'Express.js', category: 'MERN (Learning)', level: 60, order: 7 },
    { name: 'React.js', category: 'MERN (Learning)', level: 65, order: 8 },
    { name: 'MongoDB', category: 'MERN (Learning)', level: 55, order: 9 },
    { name: 'Git & GitHub', category: 'Tools', level: 80, order: 10 },
    { name: 'VS Code', category: 'Tools', level: 90, order: 11 },
    { name: 'Postman', category: 'Tools', level: 75, order: 12 },
    { name: 'Chrome DevTools', category: 'Tools', level: 75, order: 13 },
  ],

  projects: [
    {
      title: 'Jira Lite — Employee Task Scheduling System',
      slug: 'jira-lite',
      description: 'Task management system inspired by Jira. CRUD + workflow (To Do → In Progress → Completed) using core data structures.',
      longDescription:
        'Built with C++ for the backend logic and a responsive HTML/CSS/JS dashboard. Implemented sorting and searching algorithms for prioritization, and applied OOP for modular task entities.',
      technologies: ['C++', 'HTML', 'CSS', 'JavaScript', 'DSA', 'OOP'],
      category: 'Full-Stack',
      github: 'https://github.com/Muhammad-Jasim-Munir',
      liveUrl: '',
      featured: true,
      order: 1,
    },
    {
      title: 'LoopLink — Social Media System',
      slug: 'looplink',
      description: 'Full-featured social media platform inspired by Facebook. Auth, posts, likes, comments, follow system.',
      longDescription:
        'Java OOP project with JDBC + MySQL backend and a Java Swing GUI. Implemented authentication, posts, comments, likes, profile management, and follower/following relationships.',
      technologies: ['Java', 'OOP', 'JDBC', 'MySQL', 'Swing'],
      category: 'Desktop App',
      github: 'https://github.com/Muhammad-Jasim-Munir',
      featured: true,
      order: 2,
    },
    {
      title: 'Hotel Management System',
      slug: 'hotel-management',
      description: 'Console-based hotel booking and customer management system in C++.',
      technologies: ['C++', 'OOP'],
      category: 'Console App',
      github: 'https://github.com/Muhammad-Jasim-Munir',
      order: 3,
    },
    {
      title: 'Airplane Reservation System',
      slug: 'airplane-reservation',
      description: 'Flight booking system to manage passenger and reservation data.',
      technologies: ['C++', 'OOP'],
      category: 'Console App',
      github: 'https://github.com/Muhammad-Jasim-Munir',
      order: 4,
    },
    {
      title: 'E-Voting System',
      slug: 'e-voting',
      description: 'Secure voting simulation with voter authentication and counting logic.',
      technologies: ['C++', 'Structured Programming'],
      category: 'Console App',
      github: 'https://github.com/Muhammad-Jasim-Munir',
      order: 5,
    },
    {
      title: 'Student Management System',
      slug: 'student-management',
      description: 'CRUD-based system to manage student academic records with file persistence.',
      technologies: ['C++', 'File I/O'],
      category: 'Console App',
      github: 'https://github.com/Muhammad-Jasim-Munir',
      order: 6,
    },
    {
      title: 'Frontend UI Clones',
      slug: 'frontend-clones',
      description: 'Responsive UI clones — Netflix, Daraz, Spotify. Mobile-first layouts and animations.',
      technologies: ['HTML', 'CSS', 'JavaScript'],
      category: 'Frontend',
      github: 'https://github.com/Muhammad-Jasim-Munir',
      order: 7,
    },
    {
      title: 'Python Projects',
      slug: 'python-projects',
      description: 'Tax calculator and educational virus simulation built while learning Python.',
      technologies: ['Python'],
      category: 'Scripts',
      github: 'https://github.com/Muhammad-Jasim-Munir',
      order: 8,
    },
  ],

  experience: [
    {
      role: 'Software Developer — LoopLink Social Media System',
      company: 'Self-Project (OOP)',
      type: 'Self-Project',
      startDate: new Date('2024-09-01'),
      current: false,
      bullets: [
        'Developed LoopLink, a social media management system inspired by Facebook',
        'Implemented user authentication (registration/login) using JDBC and MySQL',
        'Built posts, likes, comments, and profile management features',
        'Designed follower/following system to simulate real-world social networking',
        'Created GUI using Java Swing for interactive user experience',
        'Applied OOP principles (encapsulation, inheritance, polymorphism) for scalable code',
      ],
      technologies: ['Java', 'JDBC', 'MySQL', 'Swing', 'OOP'],
      order: 1,
    },
    {
      role: 'Software Developer — Jira Lite (DSA)',
      company: 'Self-Project',
      type: 'Self-Project',
      startDate: new Date('2025-02-01'),
      current: false,
      bullets: [
        'Developed an employee task scheduling system inspired by Jira using C++',
        'Implemented task prioritization with sorting and structured data handling',
        'Designed task workflow (To Do → In Progress → Completed)',
        'Built efficient task search and update operations',
        'Applied OOP concepts to structure task entities',
      ],
      technologies: ['C++', 'DSA', 'OOP'],
      order: 2,
    },
    {
      role: 'Frontend Developer — Jira Lite Web Interface',
      company: 'Self-Project',
      type: 'Self-Project',
      startDate: new Date('2025-04-01'),
      current: true,
      bullets: [
        'Designed and developed a responsive web dashboard for the task management system',
        'Implemented CRUD operations using JavaScript and DOM manipulation',
        'Created interactive dashboard for task creation, updating, and status tracking',
        'Improved UX with structured layouts, forms, and real-time UI updates',
      ],
      technologies: ['HTML', 'CSS', 'JavaScript'],
      order: 3,
    },
  ],

  education: [
    {
      degree: 'Bachelors of Software Engineering',
      institution: 'Riphah International University',
      startYear: '2024',
      endYear: '2028',
      coursework: [
        'Web Programming',
        'Analysis of Algorithms',
        'Computer Organization & Assembly Language',
        'Data Structures & Algorithms',
        'Database Systems',
        'Software Engineering',
      ],
      order: 1,
    },
  ],

  certifications: [
    { name: 'C++ Fundamentals 2', issuer: 'CISCO', startDate: '12/2025', endDate: '01/2026', order: 1 },
    { name: 'C++ Fundamentals', issuer: 'CISCO', startDate: '01/2025', endDate: '02/2025', order: 2 },
    { name: 'Basis of Cyber Security', issuer: 'University of Engineering and Technology, Lahore', startDate: '04/2024', endDate: '06/2024', order: 3 },
  ],
};
