// Static fallback so the public site renders even if the backend is offline.
// Mirrors the seed data in backend/seed/data.js.
import type { Profile, Skill, Project, Experience, Education, Certification } from './api';

export const fallback: {
  profile: Profile; skills: Skill[]; projects: Project[];
  experience: Experience[]; education: Education[]; certifications: Certification[];
} = {
  profile: {
    name: 'Muhammad Jasim Munir',
    headline: 'Software Engineering Student · Web Developer · Backend Learner',
    location: 'Lahore, Punjab, Pakistan',
    email: 'mjmflux@icloud.com',
    phone: '+923285958656',
    summary:
      'Software Engineering student with hands-on experience in software development, focusing on data structures, algorithms, and backend system design. Built academic projects including a task scheduling system inspired by Jira. Skilled in C++, JavaScript, and web fundamentals — actively seeking a Software Engineering Internship.',
    resumeUrl: '/resume.pdf',
    socials: {
      github: 'https://github.com/Muhammad-Jasim-Munir',
      linkedin: 'http://linkedin.com/in/muhammad-jasim-enflux',
    },
  },
  skills: [
    { name: 'C++', category: 'Languages', level: 90 },
    { name: 'JavaScript', category: 'Languages', level: 80 },
    { name: 'HTML', category: 'Web', level: 90 },
    { name: 'CSS', category: 'Web', level: 85 },
    { name: 'Data Structures & Algorithms', category: 'Core CS', level: 85 },
    { name: 'Node.js', category: 'MERN (Learning)', level: 60 },
    { name: 'Express.js', category: 'MERN (Learning)', level: 60 },
    { name: 'React.js', category: 'MERN (Learning)', level: 65 },
    { name: 'MongoDB', category: 'MERN (Learning)', level: 55 },
    { name: 'Git & GitHub', category: 'Tools', level: 80 },
    { name: 'VS Code', category: 'Tools', level: 90 },
    { name: 'Postman', category: 'Tools', level: 75 },
  ],
  projects: [
    { title: 'Jira Lite — Employee Task Scheduling System', slug: 'jira-lite',
      description: 'Task management system inspired by Jira. CRUD + workflow using core data structures.',
      technologies: ['C++', 'HTML', 'CSS', 'JavaScript', 'DSA', 'OOP'],
      category: 'Full-Stack', github: 'https://github.com/Muhammad-Jasim-Munir', featured: true },
    { title: 'LoopLink — Social Media System', slug: 'looplink',
      description: 'Full-featured social media platform inspired by Facebook (Java OOP + JDBC + MySQL + Swing).',
      technologies: ['Java', 'OOP', 'JDBC', 'MySQL', 'Swing'],
      category: 'Desktop App', github: 'https://github.com/Muhammad-Jasim-Munir', featured: true },
    { title: 'Hotel Management System', slug: 'hotel-management',
      description: 'Console-based hotel booking and customer management in C++.',
      technologies: ['C++', 'OOP'], category: 'Console App',
      github: 'https://github.com/Muhammad-Jasim-Munir' },
    { title: 'Airplane Reservation System', slug: 'airplane-reservation',
      description: 'Flight booking system to manage passenger and reservation data.',
      technologies: ['C++', 'OOP'], category: 'Console App',
      github: 'https://github.com/Muhammad-Jasim-Munir' },
    { title: 'E-Voting System', slug: 'e-voting',
      description: 'Secure voting simulation with voter authentication and counting logic.',
      technologies: ['C++'], category: 'Console App',
      github: 'https://github.com/Muhammad-Jasim-Munir' },
    { title: 'Student Management System', slug: 'student-management',
      description: 'CRUD-based student record manager with file persistence.',
      technologies: ['C++', 'File I/O'], category: 'Console App',
      github: 'https://github.com/Muhammad-Jasim-Munir' },
    { title: 'Frontend UI Clones', slug: 'frontend-clones',
      description: 'Responsive UI clones — Netflix, Daraz, Spotify.',
      technologies: ['HTML', 'CSS', 'JavaScript'], category: 'Frontend',
      github: 'https://github.com/Muhammad-Jasim-Munir' },
    { title: 'Python Projects', slug: 'python-projects',
      description: 'Tax calculator and educational virus simulation (learning Python).',
      technologies: ['Python'], category: 'Scripts',
      github: 'https://github.com/Muhammad-Jasim-Munir' },
  ],
  experience: [
    { role: 'Software Developer — LoopLink Social Media System', company: 'Self-Project (OOP)', type: 'Self-Project',
      startDate: '2024-09-01', current: false,
      bullets: [
        'Developed LoopLink, a social media management system inspired by Facebook',
        'Implemented authentication using JDBC and MySQL',
        'Built posts, likes, comments, and profile management features',
        'Designed follower/following system',
        'Applied OOP principles for scalable code',
      ],
      technologies: ['Java', 'JDBC', 'MySQL', 'Swing', 'OOP'] },
    { role: 'Software Developer — Jira Lite (DSA)', company: 'Self-Project', type: 'Self-Project',
      startDate: '2025-02-01', current: false,
      bullets: [
        'Built employee task scheduling system in C++',
        'Implemented sorting + structured data for prioritization',
        'Designed task workflow (To Do → In Progress → Completed)',
        'Optimized search and update operations',
      ],
      technologies: ['C++', 'DSA', 'OOP'] },
    { role: 'Frontend Developer — Jira Lite Web Interface', company: 'Self-Project', type: 'Self-Project',
      startDate: '2025-04-01', current: true,
      bullets: [
        'Designed and developed a responsive web dashboard',
        'CRUD with vanilla JavaScript + DOM manipulation',
        'Real-time UI updates and structured forms',
      ],
      technologies: ['HTML', 'CSS', 'JavaScript'] },
  ],
  education: [
    { degree: 'Bachelors of Software Engineering', institution: 'Riphah International University',
      startYear: '2024', endYear: '2028',
      coursework: ['Web Programming', 'Analysis of Algorithms', 'Computer Organization & Assembly Language',
        'Data Structures & Algorithms', 'Database Systems', 'Software Engineering'] },
  ],
  certifications: [
    { name: 'C++ Fundamentals 2', issuer: 'CISCO', startDate: '12/2025', endDate: '01/2026' },
    { name: 'C++ Fundamentals', issuer: 'CISCO', startDate: '01/2025', endDate: '02/2025' },
    { name: 'Basis of Cyber Security', issuer: 'University of Engineering and Technology, Lahore',
      startDate: '04/2024', endDate: '06/2024' },
  ],
};
